[project]
name = "ictg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
    "pandas-stubs>=2.3.2.250926",
    "pyarrow>=21.0.0",
    "pyarrow-stubs>=20.0.0.20250928",
    "pydantic>=2.11.10",
]
